language: php

dist: bionic

php:
    - 7.3
    - nightly

cache:
    directories:
        - $HOME/.composer/cache
before_install:
    - travis_retry composer self-update
    - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

install: travis_retry composer install

script: vendor/bin/phpunit
